server:
  port: 8001

spring:
  application:
    name: microservice-cloudcinema-provider-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.105:3306/cloud_cinema
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 10
      max-wait-millis: 200
  security:
    user:
      name: aesir
      password: 123456

mybatis:
  type-aliases-package: com.aesirtech.learning.springcloud.cloudcinema.provider.user.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      # 史上巨坑 default-zone
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
